instrumentation:
  root: 'bin/'
  extensions:
    - .js
  default-excludes: true
  include-all-sources: true
  check:
    global:
      statements: 100
      lines: 100
      branches: 100
      functions: 100
  reporting:
    print: summary
    reports:
      - html
    dir: ./coverage
    report-config:
      html:
        dir: coverage
