language: node_js
node_js:
  - "4"
  - "6"

script: npm run ci
conditions:
  branch:master: npm test && npm run snyk-protect
  default: npm test

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm cache clean
